version: '2'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APPLICATION_ENV: "docker"
        ports:
            - "8181:80"
        volumes:
            - ./..:/var/www/html:rw

    mysql:
      image: mysql:5.7.22
      expose:
        - "3306"
      restart: "no"
      environment:
        MYSQL_ROOT_PASSWORD: mysql_strong_password
        MYSQL_DATABASE: materialcms
        MYSQL_USER: materialcms
        MYSQL_PASSWORD: mysql_strong_password

